import type { LanguageConfig, SupportedLanguageKey } from "../types.js";

export const LANGUAGES: Record<SupportedLanguageKey, LanguageConfig> = {
  javascript: {
    key: "javascript",
    label: "JavaScript",
    extension: "js",
    commentStyle: "block",
    blockStart: "/**",
    blockLinePrefix: " *",
    blockEnd: " */",
  },
  typescript: {
    key: "typescript",
    label: "TypeScript",
    extension: "ts",
    commentStyle: "block",
    blockStart: "/**",
    blockLinePrefix: " *",
    blockEnd: " */",
  },
  python: {
    key: "python",
    label: "Python",
    extension: "py",
    commentStyle: "line",
    linePrefix: "#",
  },
  php: {
    key: "php",
    label: "PHP",
    extension: "php",
    commentStyle: "block",
    blockStart: "/**",
    blockLinePrefix: " *",
    blockEnd: " */",
  },
  java: {
    key: "java",
    label: "Java",
    extension: "java",
    commentStyle: "block",
    blockStart: "/**",
    blockLinePrefix: " *",
    blockEnd: " */",
  },
  c: {
    key: "c",
    label: "C",
    extension: "c",
    commentStyle: "block",
    blockStart: "/**",
    blockLinePrefix: " *",
    blockEnd: " */",
  },
  cpp: {
    key: "cpp",
    label: "C++",
    extension: "cpp",
    commentStyle: "block",
    blockStart: "/**",
    blockLinePrefix: " *",
    blockEnd: " */",
  },
  shell: {
    key: "shell",
    label: "Shell",
    extension: "sh",
    commentStyle: "line",
    linePrefix: "#",
  },
  html: {
    key: "html",
    label: "HTML",
    extension: "html",
    commentStyle: "html",
    blockStart: "<!--",
    blockLinePrefix: " ",
    blockEnd: "-->",
  },
  css: {
    key: "css",
    label: "CSS",
    extension: "css",
    commentStyle: "block",
    blockStart: "/**",
    blockLinePrefix: " *",
    blockEnd: " */",
  },
};

export const LANGUAGE_OPTIONS = Object.values(LANGUAGES);
